cxx_compiler:
  - if: win
    then: vs2019
  - if: linux
    then: super_gcc

c_compiler:
  - if: win
    then: vs2019
  - if: linux
    then: super_g++

unix_level:
  - if: unix
    then: 1

python:
  - if: unix
    then:
      - "3.7"
      - "3.8"
  - if: win
    then:
      - "3.10"

cplusplus:
  - if: unix
    then:
     - "10"
     - "1000"
  - if: win
    then: "100"
