[files]
extend-exclude = [
  ".git/",
  ".pixi/",
  "**/*.snap",
  "**/*.patch",
  "tests/data/mapping_files/*",
  "test-data/conda_forge/**/*",
  "test-data/patch_application/**/*",
  "**/*.ipynb",
]
ignore-hidden = false

[default.extend-identifiers]
ratatui = "ratatui"
ND = "ND"
FreeTakServer = "FreeTakServer"
BA = "BA"
