[package]
name = "rust-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
rattler_package_streaming = { git = "https://github.com/mamba-org/rattler.git" }
rstest = "0.18.2"
serde_json = "1.0.108"
sha1 = "0.10.6"
