name: Deploy Docs

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: --html-in-header header.html


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.repository == 'prefix-dev/roar'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'


      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Setup Pages
        uses: actions/configure-pages@v3

      #  This does the following:
      #   - Replaces the docs icon with one that clearly denotes it's not the released package on crates.io
      #   - Adds a meta tag that forces Google not to index any page on the site.
      - name: Pre-docs-build
        run: |
          echo "<meta name=\"robots\" content=\"noindex\">" > header.html

      # - uses: Swatinem/rust-cache@v2
      # - name: Build Documentation
      #   run: cargo doc --workspace --no-deps --all-features
      - name: Build Book
        run: mdbook build

      #  This adds the following:
      #   - A top level redirect to the bevy crate documentation
      #   - A robots.txt file to forbid any crawling of the site (to defer to the docs.rs site on search engines).
      #   - A .nojekyll file to disable Jekyll GitHub Pages builds.
      #     echo "<meta http-equiv=\"refresh\" content=\"0; url=rattler/index.html\">" > target/doc/index.html
      #     echo "User-Agent: *\nDisallow: /" > target/doc/robots.txt

      #     mkdir final_docs
      #     touch final_docs/.nojekyll
      #     mv target/doc/* final_docs/reference
      - name: Finalize documentation
        run: |
          mv book/* final_docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'final_docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
