on:
  push:
    branches: [main, prerelase-win-fix]
  workflow_dispatch:

name: Publish Pre-release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    name: Build & Upload (${{ matrix.os }})
    env:
      SCCACHE_GHA_ENABLED: "true"
      ACTIONS_CACHE_SERVICE_V2: on
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
            cargo-home: 'D:\.cargo'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          submodules: recursive
      - name: Set short CARGO_HOME (Windows)
        if: matrix.cargo-home
        shell: bash
        run: echo "CARGO_HOME=${{ matrix.cargo-home }}" >> $GITHUB_ENV
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: packaging
          manifest-path: pixi.toml
      - name: Configure sccache
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Build package
        run: pixi run --environment=packaging build-package
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
      - name: Upload package
        run: pixi run --environment=packaging upload-package
      - name: Show sccache stats
        run: pixi run --environment=packaging sccache --stop-server
