name: Python bindings CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      # When we change pyproject.toml, we want to ensure that the maturin builds still work
      - test-data/**
      - crates/**
      - Cargo.*

      # When something in the bindings themselves changes
      - 'py-rattler-build/**/*'

      # Or when this workflow changes
      - '.github/workflows/python-bindings.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format_lint_test:
    name: Format, Lint and Test Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          manifest-path: py-rattler-build/pixi.toml
      - name: Check formatting
        working-directory: py-rattler-build
        run: |
          pixi run -e test fmt-check
      - name: Check Cargo.lock
        working-directory: py-rattler-build
        run: |
          pixi run -e test check-cargo-lock
      - name: Lint
        working-directory: py-rattler-build
        run: |
          pixi run -e test lint
      - name: Run tests
        working-directory: py-rattler-build
        run: |
          pixi run -e test test --color=yes
