name: Python bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change pyproject.toml, we want to ensure that the maturin builds still work
      - test-data/**
      - crates/**
      - Cargo.*

      # When something in the bindings themselves changes
      - "py-rattler-build/**/*"

      # Or when this workflow changes
      - ".github/workflows/python-bindings.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format_lint_test:
    name: Format, Lint and Test Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          workspaces: "py-rattler-build -> target"
          shared-key: python-bindings
          # Only save cache on main to avoid thrashing
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          manifest-path: py-rattler-build/pixi.toml
          cache: true
      - name: Check formatting
        working-directory: py-rattler-build
        run: |
          pixi run fmt-check
      - name: Check Cargo.lock
        working-directory: py-rattler-build
        run: |
          pixi run check-cargo-lock
      - name: Lint
        working-directory: py-rattler-build
        run: |
          pixi run lint
      - name: Run tests
        working-directory: py-rattler-build
        run: |
          pixi run test --color=yes
